
package ru.inslab;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "kiasSvcSoap", targetNamespace = "http://inslab.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KiasSvcSoap {


    /**
     * 
     * @param pData
     * @return
     *     returns ru.inslab.ExecProcResponse.ExecProcResult
     */
    @WebMethod(operationName = "ExecProc", action = "http://inslab.ru/ExecProc")
    @WebResult(name = "ExecProcResult", targetNamespace = "http://inslab.ru/")
    @RequestWrapper(localName = "ExecProc", targetNamespace = "http://inslab.ru/", className = "ru.inslab.ExecProc")
    @ResponseWrapper(localName = "ExecProcResponse", targetNamespace = "http://inslab.ru/", className = "ru.inslab.ExecProcResponse")
    public ru.inslab.ExecProcResponse.ExecProcResult execProc(
        @WebParam(name = "pData", targetNamespace = "http://inslab.ru/")
        String pData);

    /**
     * 
     * @param pData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecProcJson", action = "http://inslab.ru/ExecProcJson")
    @WebResult(name = "ExecProcJsonResult", targetNamespace = "http://inslab.ru/")
    @RequestWrapper(localName = "ExecProcJson", targetNamespace = "http://inslab.ru/", className = "ru.inslab.ExecProcJson")
    @ResponseWrapper(localName = "ExecProcJsonResponse", targetNamespace = "http://inslab.ru/", className = "ru.inslab.ExecProcJsonResponse")
    public String execProcJson(
        @WebParam(name = "pData", targetNamespace = "http://inslab.ru/")
        String pData);

}
