package com.lin.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-06-21T12:10:46.553+08:00
 * Generated source version: 3.2.9
 *
 */
@WebService(targetNamespace = "http://inslab.ru/", name = "kiasSvcSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface KiasSvcSoap {

    @WebMethod(operationName = "ExecProcJson", action = "http://inslab.ru/ExecProcJson")
    @RequestWrapper(localName = "ExecProcJson", targetNamespace = "http://inslab.ru/", className = "com.lin.wsdl.ExecProcJson")
    @ResponseWrapper(localName = "ExecProcJsonResponse", targetNamespace = "http://inslab.ru/", className = "com.lin.wsdl.ExecProcJsonResponse")
    @WebResult(name = "ExecProcJsonResult", targetNamespace = "http://inslab.ru/")
    public java.lang.String execProcJson(
        @WebParam(name = "pData", targetNamespace = "http://inslab.ru/")
        java.lang.String pData
    );

    @WebMethod(operationName = "ExecProc", action = "http://inslab.ru/ExecProc")
    @RequestWrapper(localName = "ExecProc", targetNamespace = "http://inslab.ru/", className = "com.lin.wsdl.ExecProc")
    @ResponseWrapper(localName = "ExecProcResponse", targetNamespace = "http://inslab.ru/", className = "com.lin.wsdl.ExecProcResponse")
    @WebResult(name = "ExecProcResult", targetNamespace = "http://inslab.ru/")
    public com.lin.wsdl.ExecProcResponse.ExecProcResult execProc(
        @WebParam(name = "pData", targetNamespace = "http://inslab.ru/")
        java.lang.String pData
    );
}
