
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lin.wsdl;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-06-21T12:10:46.505+08:00
 * Generated source version: 3.2.9
 *
 */

@javax.jws.WebService(
                      serviceName = "kiasSvc",
                      portName = "kiasSvcSoap12",
                      targetNamespace = "http://inslab.ru/",
                      wsdlLocation = "file:kiassvc.wsdl",
                      endpointInterface = "com.lin.wsdl.KiasSvcSoap")

public class KiasSvcSoap12Impl implements KiasSvcSoap {

    private static final Logger LOG = Logger.getLogger(KiasSvcSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see com.lin.wsdl.KiasSvcSoap#execProcJson(java.lang.String pData)*
     */
    public java.lang.String execProcJson(java.lang.String pData) {
        LOG.info("Executing operation execProcJson");
        System.out.println(pData);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.lin.wsdl.KiasSvcSoap#execProc(java.lang.String pData)*
     */
    public com.lin.wsdl.ExecProcResponse.ExecProcResult execProc(java.lang.String pData) {
        LOG.info("Executing operation execProc");
        System.out.println(pData);
        try {
            com.lin.wsdl.ExecProcResponse.ExecProcResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
