package com.lin.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-06-21T12:10:46.571+08:00
 * Generated source version: 3.2.9
 *
 */
@WebServiceClient(name = "kiasSvc",
                  wsdlLocation = "https://rep.absolutins.ru/FrontSvcRep/kiassvc.asmx?WSDL",

                  targetNamespace = "http://inslab.ru/")
public class KiasSvc extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inslab.ru/", "kiasSvc");
    public final static QName KiasSvcSoap12 = new QName("http://inslab.ru/", "kiasSvcSoap12");
    public final static QName KiasSvcSoap = new QName("http://inslab.ru/", "kiasSvcSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://rep.absolutins.ru/FrontSvcRep/kiassvc.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KiasSvc.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://rep.absolutins.ru/FrontSvcRep/kiassvc.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public KiasSvc(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KiasSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KiasSvc() {
        super(WSDL_LOCATION, SERVICE);
    }

    public KiasSvc(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KiasSvc(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KiasSvc(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns KiasSvcSoap
     */
    @WebEndpoint(name = "kiasSvcSoap12")
    public KiasSvcSoap getKiasSvcSoap12() {
        return super.getPort(KiasSvcSoap12, KiasSvcSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KiasSvcSoap
     */
    @WebEndpoint(name = "kiasSvcSoap12")
    public KiasSvcSoap getKiasSvcSoap12(WebServiceFeature... features) {
        return super.getPort(KiasSvcSoap12, KiasSvcSoap.class, features);
    }


    /**
     *
     * @return
     *     returns KiasSvcSoap
     */
    @WebEndpoint(name = "kiasSvcSoap")
    public KiasSvcSoap getKiasSvcSoap() {
        return super.getPort(KiasSvcSoap, KiasSvcSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KiasSvcSoap
     */
    @WebEndpoint(name = "kiasSvcSoap")
    public KiasSvcSoap getKiasSvcSoap(WebServiceFeature... features) {
        return super.getPort(KiasSvcSoap, KiasSvcSoap.class, features);
    }

}
