
package com.lin.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.lin.XmlUtils;
import com.lin.bean.AuthRequest;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-06-21T12:10:46.403+08:00
 * Generated source version: 3.2.9
 *
 */
public final class KiasSvcSoap_KiasSvcSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://inslab.ru/", "kiasSvc");

    private KiasSvcSoap_KiasSvcSoap12_Client() {
    }

//    public static void main(String args[]) throws java.lang.Exception {
//
//
//
//
//        URL wsdlURL = KiasSvc.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//
//        KiasSvc ss = new KiasSvc(wsdlURL, SERVICE_NAME);
//        KiasSvcSoap port = ss.getKiasSvcSoap();
//
//
//
//        {
//        System.out.println("Invoking execProcJson...");
//        java.lang.String _execProcJson_pData = "";
//            BindingProvider bp = (BindingProvider) port;
//            Map<String, Object> context = bp.getRequestContext();
//            context.put(BindingProvider.USERNAME_PROPERTY, "Voshod");
//            context.put(BindingProvider.PASSWORD_PROPERTY, "555b8d85cef");
//            com.lin.wsdl.ExecProcResponse.ExecProcResult _execProc__return = port.execProc(_execProcJson_pData);
//            System.out.println("execProc.result=" + _execProc__return);
//
////            System.out.println("execProcJson.result=" + _execProcJson__return);
//
//
//        }
////        AuthRequest authRequest = new AuthRequest();
////        AuthRequest.Params params = new AuthRequest.Params();
////        params.setName("Voshod");
////        params.setPwd("9abd71a0dbf0eeff2463f0d8e6938d153a673a9f587b403fced6ff88dc171a401a768f8bf203f57b3d0cbfc7c3560d272038f3288f9604c43f9a79014f1cb4e3");
////        params.setSid("");
////        authRequest.setParams(params);
////        authRequest.setAppId(221392);
////        authRequest.setRequestIp("183.14.29.140");
////        authRequest.setReqName("Auth");
////        String xle ="<![CDATA[<data>" +  XmlUtils.toXml(authRequest)  + "</data>]]>";
////
////
////        {
////        System.out.println("Invoking execProc...");
////        java.lang.String _execProc_pData = xle;
////        com.lin.wsdl.ExecProcResponse.ExecProcResult _execProc__return = port.execProc(_execProc_pData);
////        System.out.println("execProc.result=" + _execProc__return);
//
////
////        }
////
////        System.exit(0);
//    }

}
