
package com.lin.wsdl2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import com.lin.wsdl.KiasSvc;
import com.lin.wsdl.KiasSvcSoap;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

/**
 * This class was generated by Apache CXF 3.2.9
 * 2019-06-21T12:10:46.403+08:00
 * Generated source version: 3.2.9
 *
 */
public final class KiasSvcSoap_KiasSvcSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://inslab.ru/", "kiasSvc");

    private KiasSvcSoap_KiasSvcSoap12_Client() {
    }

//    public static void main(String args[]) throws Exception {
//
//
//    }

}
