
package com.lin.wsdl2;

import ru.inslab.KiasSvcSoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "kiasSvc", targetNamespace = "http://inslab.ru/", wsdlLocation = "https://rep.absolutins.ru/FrontSvcRep/kiassvc.asmx?WSDL")
public class KiasSvc
    extends Service
{

    private final static URL KIASSVC_WSDL_LOCATION;
    private final static WebServiceException KIASSVC_EXCEPTION;
    private final static QName KIASSVC_QNAME = new QName("http://inslab.ru/", "kiasSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://rep.absolutins.ru/FrontSvcRep/kiassvc.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KIASSVC_WSDL_LOCATION = url;
        KIASSVC_EXCEPTION = e;
    }

    public KiasSvc() {
        super(__getWsdlLocation(), KIASSVC_QNAME);
    }

    public KiasSvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), KIASSVC_QNAME, features);
    }

    public KiasSvc(URL wsdlLocation) {
        super(wsdlLocation, KIASSVC_QNAME);
    }

    public KiasSvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KIASSVC_QNAME, features);
    }

    public KiasSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KiasSvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KiasSvcSoap
     */
    @WebEndpoint(name = "kiasSvcSoap")
    public KiasSvcSoap getKiasSvcSoap() {
        return super.getPort(new QName("http://inslab.ru/", "kiasSvcSoap"), KiasSvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KiasSvcSoap
     */
    @WebEndpoint(name = "kiasSvcSoap")
    public KiasSvcSoap getKiasSvcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://inslab.ru/", "kiasSvcSoap"), KiasSvcSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KIASSVC_EXCEPTION!= null) {
            throw KIASSVC_EXCEPTION;
        }
        return KIASSVC_WSDL_LOCATION;
    }

}
